services:
  - type: web
    name: shopify-tracking-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_SHOP
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true 